-- Author: Daniel Grammer
-- Date Created: 2/4/2025
-- Date Last Edited: 2/4/2025

-- ---------------------------- --
# Script for Creating Stored Procedure Logging Table
-- ---------------------------- --

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE TABLE IF NOT EXISTS `t_proc_log` (
	`run_id` VARCHAR(36) NOT NULL COMMENT "Unique proc run identifier",
	`proc_name` VARCHAR(20) NOT NULL COMMENT "Name of proc executed", 
    `params` TEXT NOT NULL COMMENT "List of parameters passed to proc",
    `msg` TEXT NOT NULL COMMENT "Messages generated by the proc",
    `rows_modified` INT NOT NULL COMMENT "Number of rows modified by the proc", 
    `stat_c` VARCHAR(1) NOT NULL COMMENT "Status code of proc (C or I)",
    `usr` VARCHAR(100) NOT NULL COMMENT "User who called the proc", 
    `beg_ts` DATETIME NOT NULL COMMENT "Timestamp of proc call", 
    `end_ts` DATETIME NOT NULL COMMENT "Timestamp of proc completion",
    PRIMARY KEY (`run_id`),
    UNIQUE INDEX `run_id_UNIQUE` (`run_id` ASC) VISIBLE)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;